[tool.poetry]
name = "tdd project"
version = "0.0.1"
description = ""
<<<<<<< HEAD
authors = ["Nayanna Nara <nayanna501@gmail.com>"]
=======
authors = ["DanielViniAssis <dvs.daniel11@gmail.com>"]
>>>>>>> f44af51a971f61c5e771acb97d8ff8fdabaf3363
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
<<<<<<< HEAD
fastapi = "^0.104.1"
uvicorn = "^0.24.0.post1"
pydantic = "^2.5.1"
pydantic-settings = "^2.1.0"
motor = "^3.3.1"
pytest = "^7.4.3"
pytest-asyncio = "^0.21.1"
pre-commit = "^3.5.0"
httpx = "^0.25.1"

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = [
  "--strict-config",
  "--strict-markers",
  "--ignore=docs_src",
]
xfail_strict = true
junit_family = "xunit2"
=======
fastapi = "^0.111.1"
uvicorn = "^0.30.1"
pydantic = "^2.8.2"
pydantic-settings = "^2.3.4"
motor = "^3.5.1"
pytest = "^8.2.2"
pytest-asyncio = "^0.23.7"
pre-commit = "^3.7.1"

>>>>>>> f44af51a971f61c5e771acb97d8ff8fdabaf3363

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
